# Generated by Django 3.1.3 on 2021-02-07 14:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_subcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 7, 14, 38, 13, 132288, tzinfo=utc), editable=False),
        ),
        migrations.AddField(
            model_name='product',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 7, 14, 38, 13, 132317, tzinfo=utc)),
        ),
    ]
