# Generated by Django 3.0.8 on 2020-10-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_item_pr_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='imgsrc',
            field=models.CharField(default='', max_length=3000),
        ),
    ]
