# Generated by Django 3.1.3 on 2021-02-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_auto_20201106_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sale_price',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
