# Generated by Django 3.1.3 on 2021-02-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_auto_20210201_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='sale_price',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
